#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 05, 2018 10:00:25 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global che63
    che63 = StringVar()
    global che64
    che64 = StringVar()
    global combobox
    combobox = StringVar()
    global height
    height = StringVar()
    global weight
    weight = StringVar()
    global che42
    che42 = StringVar()
    global che43
    che43 = StringVar()

def calcBMI():
    print('Menu_support.calcBMI')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Menu
    Menu.vp_start_gui()


